#define CMAKE_BUILD

#cmakedefine HAVE_REGEX 1

#cmakedefine CURSES_HAVE_NCURSESW_CURSES_H 1
#cmakedefine CURSES_HAVE_NCURSESW_H 1
#cmakedefine CURSES_HAVE_NCURSES_CURSES_H 1
#cmakedefine CURSES_HAVE_NCURSES_H 1
#cmakedefine CURSES_HAVE_CURSES_H 1

#cmakedefine PACKAGE_VERSION "${PACKAGE_VERSION}"

#ifdef CURSES_HAVE_NCURSESW_CURSES_H
#  define HAVE_NCURSESW_CURSES_H  CURSES_HAVE_NCURSESW_CURSES_H
#endif
#ifdef CURSES_HAVE_NCURSESW_H
#  define HAVE_NCURSESW_H         CURSES_HAVE_NCURSESW_H
#endif
#ifdef CURSES_HAVE_NCURSES_CURSES_H
#  define HAVE_NCURSES_CURSES_H   CURSES_HAVE_NCURSES_CURSES_H
#endif
#ifdef CURSES_HAVE_NCURSES_H
#  define HAVE_NCURSES_H          CURSES_HAVE_NCURSES_H
#endif
#ifdef CURSES_HAVE_CURSES_H
#  define HAVE_CURSES_H           CURSES_HAVE_CURSES_H
#endif
